name: "Build & test"

on:
  # TODO: setup trigger tu run this job for every pull request
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup gcc"
      shell: bash
      run: /
        sudo apt update
        sudo apt install gcc-10 g++-10
    - name: "Test projekt"
      run: make test

    # TODO: run tests

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Setup gcc"
      shell: bash

      run: /
        sudo apt update
        sudo apt install gcc-10 g++-10

    - name: "Build projekt"
      run: make build
    # TODO: setup compiler

    # TODO: build project
