name: "Build & test"

on:
  # TODO: setup trigger tu run this job for every pull request

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    # TODO: setup compiler

    # TODO: run tests

  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    # TODO: setup compiler

    # TODO: build project
