name: "Release"

on:
  push:
    tags: # run when release has been tagged, however ignore non-official semver tags (release candidates etc)
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    # TODO: setup compiler

    # TODO: run tests

    # TODO: build project

    # TODO: release
